### ISSUE TITLE
Add documentation for VCarousel Component

### ISSUE THREAD

**Issue by gsi-chao** [gsi-chao/gsi-ui#306]
Add documentation for VCarousel Component

**Comment by gsi-lozano** [comment]
Started 02/27/2020 9:30 am

**Comment by gsi-lozano** [comment]
Started 02/27/2020 9:30 am

**Comment by gsi-lozano** [comment]
Ended 02/27/2020 12:00 m
- Create Table Api for compoent properties documentation
- Added api for Steps and Carousel
