### ISSUE TITLE
Create autocomplete select/multiselect field

### ISSUE THREAD

**Issue by gsi-chao** [gsi-chao/gsi-ui#313]
Create an autocomplete select/multi-select field using this component.
https://bit.dev/primefaces/primereact/autocomplete?example=5d42e64160fbc6001439e687

Install this in the library: https://bit.dev/primefaces/primereact/autocomplete?example=5d42e64160fbc6001439e687

**Comment by gsi-yoendy** [comment]
Started: 3/2/2020 at 10:46AM

**Comment by gsi-chao** [comment]
Completed
